version: 0.1
# This is the configuration for V2
storage:
    filesystem:
        rootdirectory: /data
    cache:
        layerinfo: redis
http:
    addr: localhost:5000
    secret: <secret>
redis:
    addr: <redis_ip>:6379

# This is the configuration for V1
production:
    storage: local
    storage_path: /data
    issue: '"docker-registry server"'
    # Default log level is info
    loglevel: info
    # Enable debugging (additional informations in the output of the _ping endpoint)
    debug: false
    # By default, the registry acts standalone (eg: doesn't query the index)
    standalone: true

    cache:
        host: <redis_ip>
        port: 6379
        db: 0

    # Enabling LRU cache for small files
    # This speeds up read/write on small files
    # when using a remote storage backend (like S3).
    cache_lru:
        host: <redis_ip>
        port: 6379
        db: 1
